
# NMAKE makefile for Microsoft Visual C

LIBDIR = ..\lib
INCDIR = ..\include

CFEXTRA = -MT

!IFDEF NATIVE_THREADS
CFEXTRA += -DNATIVE_THREADS
!ENDIF

CC = cl
!IFDEF DEBUG
CFLAGS = -I$(INCDIR) -WX -nologo -W3 -Od -Zi -Fd$(LIBDIR)\dynm32.pdb $(CFEXTRA)
!ELSE
CFLAGS = -I$(INCDIR) -WX -nologo -W3 -O2 $(CFEXTRA)
!ENDIF


.SUFFIXES: .d .c .h .obj .exe .lib


.d.c .PRECIOUS :
	dpp $(STRAT) -C -g $(INCDIR)\generics.h -p $<

CLASSES = 

OBJ = $(CLASSES:.d=.obj) regutil.obj regutil2.obj

curlib.cm : $(OBJ)
	lib /nologo /out:$(LIBDIR)\dwdsnm.lib $(LIBDIR)\dwdsnm.lib $?
	-del /q *.obj 2>nul
	echo Done >$@

newgens:
	dpp $(STRAT) -C -g $(INCDIR)/generics.h -p *.d

regutl32.exe : regutil.c
	cl -nologo -Zi -Od -DMAIN $< advapi32.lib user32.lib -Fe$@
	-del /q *.obj  2>nul

clean :
	-del /q *.obj generics.* *.o *.pdb *.err 2>nul
	-del /q *.~ *.?~ *.??~ *.{* *.bak #*.* 2>nul

realclean : clean
	-del /q curlib.* 2>nul
