#  Makefile designed for use by the NMAKE.EXE utility and
#  Microsoft Visual C/C++

DYNINC = $(DYNACE_PATH)\include


C_SRC = makeguid.c

CLASS_SRC = ComClient.d ComServer.d ComInterface.d ComInstance.d OLEDispatch.d OLEClient.d


LIBDIR = ..\lib
INCDIR = ..\include

CFEXTRA = -MT

!IFDEF NATIVE_THREADS
CFEXTRA += -DNATIVE_THREADS
!ENDIF


!IFDEF	DEBUG
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -D_WINDOWS -Od -Zi -Fd$(LIBDIR)\dynm32.pdb $(CFEXTRA)
GFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -Oityb1 -Gs -Gy -D_WINDOWS -Zi -Fd$(LIBDIR)\dynm32.pdb
LFLAGS = /nologo /subsystem:windows /debug
!ELSE
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -O2 -D_WINDOWS $(CFEXTRA)
GFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -Oityb1 -Gs -Gy -D_WINDOWS
LFLAGS = /nologo /subsystem:windows
!ENDIF

OBJS = $(CLASS_SRC:.d=.obj) $(C_SRC:.c=.obj)

CC = cl

.SUFFIXES: .d .c .h .obj .exe .lib

.d.c :
	dpp $(STRAT) -g $(INCDIR)\generics.h -t -p $<

.c.obj:
	$(CC) $(CFLAGS) $<

.d.obj:
	dpp $(STRAT) -C -g $(INCDIR)\generics.h -t -p $<
	$(CC) $(CFLAGS) $*.c

.rc.res:
	rc $<

allok.nm : $(INCDIR)\generics.h curlib.nm
	echo Done >$@


curlib.nm : $(OBJS)
!IFDEF  NEW
	lib /nologo /out:$(LIBDIR)\dwdsnm.lib $?
!ELSE
	lib /nologo /out:$(LIBDIR)\dwdsnm.lib $(LIBDIR)\dwdsnm.lib $?
!ENDIF
	-del /q *.obj 2>nul
	echo Done >$@

main.obj : resource.h


$(INCDIR)\generics.h : $(CLASS_SRC)
	dpp $(STRAT) -C -g $(INCDIR)\generics.h -t $(INCDIR)\generics.h -h $(INCDIR)\generics.h -p $**


generics.c : generics.h
	dpp $(STRAT) -g -c -Isc windows.h sql.h sqlext.h

generics.obj : generics.c
	$(CC) -c $(GFLAGS) $<

newgens : 
	dpp $(STRAT) -C -g $(INCDIR)\generics.h -h $(INCDIR)\generics.h -p $(CLASS_SRC)

makegens:
	dpp $(STRAT) -C -g $(INCDIR)\generics.h -h $(INCDIR)\generics.h -s $(CLASS_SRC)

clean:
	-del /q *.obj 2>nul
	-del /q *.exe 2>nul
	-del /q *.ex1 2>nul
	-del /q *.res 2>nul
	-del /q *.aps 2>nul
	-del /q *.pdb 2>nul
	-del /q *.wsp 2>nul
	-del /q *.ilk 2>nul
	-del /q *.bsc 2>nul
	-del /q *.vcp 2>nul
	-del /q *.pch 2>nul
	-del /q *.sbr 2>nul
	-del /q *.vcw 2>nul
	-del /q *.map *.ncb 2>nul
	-rmdir /s /q WinDebug 2>nul
	-rmdir /s /q WinRel 2>nul
	-del /q *.~ *.?~ *.??~ *.{* *.bak #*.* 2>nul


realclean: clean
	-del /q curlib.* allok.* $(CLASS_SRC:.d=.c) generics.c generics.h generics.1 2>nul

