#  Makefile designed for use by the NMAKE.EXE utility and		-*-Makefile-*-
#  Microsoft Visual C


TARGET = main


C_SRC = main.c


#DYNACE_PATH = ...

CC = cl

CFEXTRA = -MT

!IFDEF NATIVE_THREADS
CFEXTRA += -DNATIVE_THREADS
!ENDIF

BINDIR = $(DYNACE_PATH)\bin
LIBDIR = ..\..\lib
INCDIR = ..\..\include
DYNINC = $(DYNACE_PATH)\include


!IFDEF	DEBUG
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -Zi -D_WINDOWS $(CFEXTRA)
LFLAGS = /nologo /subsystem:windows /debug
!ELSE
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -O2 -D_WINDOWS $(CFEXTRA)
LFLAGS = /nologo /subsystem:windows
!ENDIF


LIBS = $(LIBDIR)\dwdsnm.lib $(DYNACE_PATH)\lib\dynlcm.lib

MSLIBS = kernel32.lib user32.lib gdi32.lib comdlg32.lib comctl32.lib advapi32.lib \
         shell32.lib mpr.lib msimg32.lib

OBJS = $(C_SRC:.c=.obj)


RESOURCES = $(TARGET).res

.SUFFIXES: .c .obj .exe .rc .res

.rc.res:
	rc $<

.c.obj:
	$(CC) $(CFLAGS) $<

$(TARGET).exe : $(OBJS) $(RESOURCES) $(LIBS)
	link /out:$@ $(LFLAGS) $(OBJS) $(LIBS) $(MSLIBS) $(RESOURCES)


$(OBJS) : resource.h


clean:
	-del /q *.obj 2>nul
	-del /q *.exe 2>nul
	-del /q *.ex1 2>nul
	-del /q *.res 2>nul
	-del /q *.aps 2>nul
	-del /q *.pdb 2>nul
	-del /q *.wsp 2>nul
	-del /q *.ilk 2>nul
	-del /q *.bsc 2>nul
	-del /q *.vcp 2>nul
	-del /q *.pch 2>nul
	-del /q *.sbr 2>nul
	-del /q *.vcw 2>nul
	-del /q *.map 2>nul
	-rmdir /s /q WinDebug 2>nul
	-rmdir /s /q WinRel 2>nul
	-del /q *.idb *.mdp *.ncb 2>nul
	-del /q *.dsw *.opt *.plg 2>nul
	-del /q *.dsp 2>nul
	-del /q *.sln 2>nul
