#  Makefile designed for use by the NMAKE.EXE utility and		-*-Makefile-*-
#  Microsoft Visual C


TARGET = main


C_SRC = main.c


#DYNACE_PATH = ...

CC = cl

CFEXTRA = -MT

!IFDEF NATIVE_THREADS
CFEXTRA += -DNATIVE_THREADS
!ENDIF

BINDIR = $(DYNACE_PATH)\bin
LIBDIR = ..\..\lib
INCDIR = ..\..\include
DYNINC = $(DYNACE_PATH)\include


!IFDEF	DEBUG
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -Zi -D_WINDOWS $(CFEXTRA)
LFLAGS = /nologo /subsystem:windows /debug
!ELSE
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -O2 -D_WINDOWS $(CFEXTRA)
LFLAGS = /nologo /subsystem:windows
!ENDIF


LIBS = $(LIBDIR)\dwdsnm.lib $(DYNACE_PATH)\lib\dynlcm.lib

MSLIBS = kernel32.lib user32.lib gdi32.lib comdlg32.lib comctl32.lib advapi32.lib \
         shell32.lib mpr.lib msimg32.lib

OBJS = $(C_SRC:.c=.obj)


RESOURCES = $(TARGET).res

.SUFFIXES: .c .obj .exe .rc .res

.rc.res:
	rc $<

.c.obj:
	$(CC) $(CFLAGS) $<

$(TARGET).exe : $(OBJS) $(RESOURCES) $(LIBS)
	link /out:$@ $(LFLAGS) $(OBJS) $(LIBS) $(MSLIBS) $(RESOURCES)


$(OBJS) : resource.h


clean:
	rm -zq *.obj
	rm -zq *.exe
	rm -zq *.ex1
	rm -zq *.res
	rm -zq *.aps
	rm -zq *.pdb
	rm -zq *.wsp
	rm -zq *.ilk
	rm -zq *.bsc
	rm -zq *.vcp
	rm -zq *.pch
	rm -zq *.sbr
	rm -zq *.vcw
	rm -zq *.map
	rm -zqr WinDebug
	rm -zqr WinRel
	rm -zq *.idb *.mdp *.ncb
	rm -zq *.dsw *.opt *.plg
	rm -zq *.dsp
	rm -zq *.sln
