

# NMAKE makefile for Microsoft Visual C


BINDIR = ..\bin
LIBDIR = ..\lib
INCDIR = ..\include

CFEXTRA = -MT

!IFDEF NATIVE_THREADS
CFEXTRA += -DNATIVE_THREADS
!ENDIF

!IFDEF DEBUG
CFLAGS = -I$(INCDIR) -I$(DYNACE_PATH)\include -nologo -Od -Zi -Fd$(LIBDIR)\dynm32.pdb $(CFEXTRA)
!ELSE
CFLAGS = -I$(INCDIR) -I$(DYNACE_PATH)\include -nologo -Oityb1 -Gs -Gy $(CFEXTRA)
!ENDIF

curlib.cm : $(INCDIR)\generics.h
	$(DYNACE_PATH)\bin\dpp $(STRAT) -C -g $(INCDIR)\generics.h -c -h
	$(CC) -c $(CFLAGS) generics.c
	lib /nologo /out:$(LIBDIR)\dwdsnm.lib $(LIBDIR)\dwdsnm.lib generics.obj
	-del /q *.obj generics.* 2>nul
	echo Done >$@

clean:
	-del /q *.obj generics.* *.o *.pdb *.err 2>nul
	-del /q *.~ *.?~ *.??~ *.{* *.bak #*.* 2>nul

realclean : clean
	-del /q curlib.* 2>nul
