
#  Makefile designed for use by the NMAKE.EXE utility and
#  Microsoft Visual C


C_SRC = main.c flash.c jsfl.c


BINDIR = $(DYNACE_PATH)\bin
LIBDIR = ..\lib
INCDIR = ..\include
DYNINC = $(DYNACE_PATH)\include

!IFDEF	DEBUG
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -Zi -Od -D_WINDOWS -MT
LFLAGS = /nologo /subsystem:windows /debug
!IFDEF INTEGRA
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -Zi -Od -D_WINDOWS -DINTEGRA -MT
!ENDIF
!ELSE
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -O2 -D_WINDOWS -MT
LFLAGS = /nologo /subsystem:windows
!IFDEF INTEGRA
CFLAGS = -nologo -c -I$(INCDIR) -I$(DYNINC) -WX -O2 -D_WINDOWS -DINTEGRA -MT
!ENDIF
!ENDIf


LIBS = $(LIBDIR)\dwdsnm.lib $(DYNACE_PATH)\lib\dynlcm.lib

MSLIBS = kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib comctl32.lib advapi32.lib \
         shell32.lib wsock32.lib odbc32.lib winmm.lib ole32.lib wininet.lib rpcrt4.lib mpr.lib msimg32.lib

OBJS = $(C_SRC:.c=.obj)

RESOURCES = main.res

.rc.res:
	rc /nologo $<

cld.exe : $(OBJS) $(RESOURCES) $(LIBS)
	link /out:$@ $(LFLAGS) $(OBJS) $(LIBS) $(MSLIBS) $(RESOURCES)


$(OBJS) : resource.h

$(OBJS) : ../windows/ctlsave.h


realclean clean:
	-del /q *.obj 2>nul
	-del /q *.exe 2>nul
	-del /q *.ex1 2>nul
	-del /q *.res 2>nul
	-del /q *.aps 2>nul
	-del /q *.pdb 2>nul
	-del /q *.wsp 2>nul
	-del /q *.ilk 2>nul
	-del /q *.bsc 2>nul
	-del /q *.vcp 2>nul
	-del /q *.pch 2>nul
	-del /q *.sbr 2>nul
	-del /q *.vcw 2>nul
	-del /q *.map 2>nul
	-del /q generics.* 2>nul
	-rmdir /s /q WinDebug 2>nul
	-rmdir /s /q WinRel 2>nul
	-del /q *.idb *.mdp *.ncb 2>nul
	-del /q *.dsw *.opt *.plg 2>nul
	-del /q *.dsp 2>nul

